# Generated by Django 5.2 on 2025-04-08 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_entryrequirement_university_programme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='entry_requirement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.entryrequirement'),
        ),
    ]
