# Generated by Django 5.2 on 2025-04-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_programme_entry_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmetag',
            name='relevancy_score',
            field=models.IntegerField(default=5),
        ),
    ]
