# Generated by Django 5.2 on 2025-04-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_programmetag_relevancy_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='label',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
