# Generated by Django 5.2 on 2025-04-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_tag_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='label',
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preference_score',
            field=models.IntegerField(null=True),
        ),
    ]
