# Generated by Django 5.2 on 2025-05-08 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_tag_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='programme',
            name='degree_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.degreefield'),
        ),
    ]
