# Generated by Django 5.2 on 2025-05-08 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_degreefield_programme_degree_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagDegreeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevancy_score', models.IntegerField(default=0)),
                ('degree_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.degreefield')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tag')),
            ],
        ),
    ]
