# Generated by Django 5.2 on 2025-05-09 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_tagdegreefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.university'),
        ),
    ]
