# Generated by Django 5.2 on 2025-05-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_programme_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='degreefield',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
