# Generated by Django 5.2 on 2025-05-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_degreefield_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryrequirement',
            name='spm',
        ),
        migrations.AlterField(
            model_name='entryrequirement',
            name='diploma',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='entryrequirement',
            name='matriculation',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='entryrequirement',
            name='stpm',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
