# Generated by Django 5.2 on 2025-05-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_entryrequirement_spm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryrequirement',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
