# Generated by Django 5.2 on 2025-05-10 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_entryrequirement_explanation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entryrequirement',
            old_name='explanation',
            new_name='explaination',
        ),
    ]
