# Generated by Django 5.2 on 2025-05-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_explanation_entryrequirement_explaination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='career_opportunities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
