# Generated by Django 5.2 on 2025-05-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_programme_career_opportunities'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='logo',
            field=models.URLField(default='https://placehold.co/500x500', max_length=500),
        ),
    ]
