# Generated by Django 5.2 on 2025-06-07 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_university_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgrammeTag',
        ),
    ]
