# Generated by Django 5.2 on 2025-06-12 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_delete_programmetag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text_1', models.TextField(help_text='Main question text or label.')),
                ('question_text_2', models.TextField(blank=True, help_text='Secondary statement, if any (e.g., for scale questions).', null=True)),
                ('question_type', models.CharField(choices=[('SCALE_1_5', 'Scale 1 to 5'), ('YES_NO', 'Yes/No Question')], help_text='Type of question, determines rendering and answer format.', max_length=20)),
                ('question_number', models.PositiveIntegerField(help_text='Order/number of the question.', unique=True)),
                ('tag', models.ForeignKey(help_text='The Tag this question relates to.', on_delete=django.db.models.deletion.CASCADE, to='app.tag')),
            ],
        ),
    ]
