# Generated by Django 5.2.2 on 2025-06-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
